config/routes.rb
ArtisanMarket::Application.routes.draw do
  
  resources :attribute_layers

  resources :attributes

  devise_for :users

  get "pages/home"
  get "pages/about"
  get "pages/contact"

  resources :products
  resources :projects do
    member do 
      post :attribute_layer
      get :palette
      get :category
    end
  end
  resources :product_categories
  resources :palettes
  resources :attribute_layers
  resources :attributes
  resources :catalogues
  resources :design_versions

  root to: 'pages#home'

end

app/models/palette.rb
class Palette < ActiveRecord::Base
  attr_accessible :label, :product_category_id,
                  :attribute_layers_attributes
  
  has_many :attribute_layers

  belongs_to :artisan,  class_name: 'User'
  has_one    :product_category
  
  accepts_nested_attributes_for :attribute_layers

end

app/controllers/palettes_controller.rb
class PalettesController < ApplicationController

before_filter :authenticate_user!

  def index
    @palettes = Palette.where(user_id: current_user.id)
  end

  def show
    @palette = Palette.find(params[:id])
    @attribute_layers = @palette.attribute_layers
    @ids = @attribute_layers.map { |layer| layer.id }
    @attributes = Attribute.all.select {|attr| @ids.include?(attr.id) }
  end


  def new
    @palette = Palette.new
    # @product_category = ProductCategory.new
    @palette.attribute_layers.build
  end

  def edit
    @palette = Palette.find(params[:id])
  end

  def create
    @palette = Palette.new(params[:palette])
    @palette.user = current_user
    @palette.save
    session[:palette_id] = @palette.id
    # if session[:project_id]
    #   Project.find(session[:project_id]).update_attribute :palette_id, @palette.id
    #   session.delete(:project_id)
    # end
    redirect_to edit_palette_path(@palette)
  end

  def update
    @palette = Palette.find(params[:id])
    @attribute_layer = @palette.attribute_layer.find()
  end

  def destroy
    @palette = Palette.find(params[:id])
    @palette.destroy
    redirect_to action: :index
  end

end

app/helpers/palettes_helper.rb
module PalettesHelper
end

app/views/palettes/edit.html.erb
      

      <div class="row span12 bordered" id="design">
        

        <div class="span2" id="pallete">

        </div>











<!--         <div class="span9 unselectable" id="canvas_container">
          <button class="btn pull-left" id="reset">Reset</button>
          <button class="btn pull-left" id="remove-img">Remove Image</button>
          <button class="btn pull-left" id="switch">Switch User</button>
          <%= form_for @palette, :url => { action: :update }, :html => { :multipart => true } do |form| %>
            <%= form.file_field :base_image %>
            <%= form.button "Upload Image" %>

          <% end %>


          <button class="btn pull-left" id="save-project">Save Project</button>

          <canvas id="canvas"></canvas> -->
        </div>
      </div> <!-- /row -->

app/views/palettes/index.html.erb
<h3>Listing palettes for <%= current_user.name %> </h3>
 
<table class="projects-table">
  <tr>
    <th>Palette Name</th>
    <th>Product Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @palettes.each do |palette| %>
  <tr>
    <td><%= palette.label %></td>
    <td><%= palette.product_category.label %></td>

    <td><%= link_to 'Show', palette %></td>
    <td><%= link_to 'Edit', edit_palette_path(palette) %></td>
    <td><%= link_to 'Remove', palette, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Palette', new_palette_path %>




<style>
.projects-table tr td{
    padding: 15px;
}
</style>

app/views/palettes/new.html.erb
----

<%= simple_form_for @palette do |f| %>
  
  <%= f.input :label %>
  <%= f.association :product_category, 
                    collection: ProductCategory.all, 
                    value_method: :_id, 
                    label_method: :label %>
  <%= f.label "Attribute Layers"%>
  <%= f.collection_check_boxes :attribute_layer_ids, AttributeLayer.all, :id, :label, item_wrapper_class: 'inline' %>
  
  <%= f.button :submit, "Create and continue" %>

<% end %>




<style>
textarea, input {
    max-height: 200px;
    width: 400px;
}
</style>

<script>
$(document).ready(function() {

    $("select").append($("<option></option>").attr("value", -1).text("Create New Category"));
    $("#new_product_category").hide();
    $("#palette_product_category_id").on("change", function() {
        if(this.selectedIndex == this.options.length-1) {
            $("#new_product_category").show();
            return false;
        }
        $("#new_product_category").hide();
    });



    $("#create_category").click(function(event){
      // event.preventDefault();
      console.log($("#new_product_category"));
      console.log($("#new_product_category").attr('action'));
      console.log($("#new_product_category").serialize());
      // var value = $(".category_value").val();
      var valuesToSubmit = $("#new_product_category").serialize();
      $.ajax({
        type: 'POST',
        url: $("#new_product_category").attr('action'),
        data: valuesToSubmit,
        // dataType: "JSON",
        success: function(data){
          var value = $(".category_value").val();
          console.log("value: " + value);

          // var index = $("#palette_product_category_id").children().length-3;
          // console.log(index);
          // console.log($("#palette_product_category_id options:eq("+index+")"));
          // $("#palette_product_category_id options:eq("+index+")").prop('selected', true);
          $("#palette_product_category_id").attr("value", 1);
          $("#new_product_category").hide();

        }
      });

      // $("#new_product_category").trigger('submit.rails');
      return false;
    });




});
  

</script>

app/views/palettes/show.html.erb
      

      <div class="row span12 bordered" id="design">
        <div class="span2" id="pallete">
          <%= @palette.label %>

          <div class="menu_ bordered">

            <%= select_tag :palette, options_from_collection_for_select(@attribute_layers, :id, :label), include_blank: true, id: 'attr-layer-select' %>
    
              <% @attributes.each do |attribute| %>
              <%= image_tag attribute.attr_img.url(:thumb), class: "#{attribute.attribute_layer.id} attr_" %>
              <% end %>

          </div>
        </div>


        <div class="span9" id="canvas_container_">
          <%= link_to 'New Attribute', new_attribute_path %>
          <br />
          <%= link_to 'New AttributeLayer', new_attribute_layer_path %>

        </div>
      </div> <!-- /row -->

<style>
#canvas_container_ {
    min-height: 700px;
    /*border: inherit;*/
    width: 700px;
}
</style>

<script>

    $("#attr-layer-select").on("change", function() {
        // var self = $("#attr-layer-select");
        console.log("here");
        console.log(this.options[this.selectedIndex].value);
        var class_val = this.options[this.selectedIndex].value;
        var all_elements = $(".attr_");
        console.log(all_elements);
        all_elements.hide();
        var sel_elements = $("."+class_val);
        sel_elements.show();
        console.log(sel_elements);

    });

</script>