config/routes.rb
ArtisanMarket::Application.routes.draw do
  
  resources :attribute_layers

  resources :attributes

  devise_for :users

  get "pages/home"
  get "pages/about"
  get "pages/contact"

  resources :products
  resources :projects do
    member do 
      post :attribute_layer
      get :palette
      get :category
    end
  end
  resources :product_categories
  resources :palettes
  resources :attribute_layers
  resources :attributes
  resources :catalogues
  resources :design_versions

  root to: 'pages#home'

end

app/models/palette.rb
class Palette < ActiveRecord::Base
  attr_accessible :label, :product_category_id,
                  :attribute_layers_attributes
  
  has_many :attribute_layers

  belongs_to :artisan,  class_name: 'User'
  has_one    :product_category
  
  accepts_nested_attributes_for :attribute_layers

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name, :artisan_id, :img_file, :product_category_id, :palette_id,
                  :product_category_attributes, :palette_attributes

  has_attached_file :img_file, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  
  after_save :notify_artisans
  
  belongs_to :customer, class_name: 'User'
  belongs_to :artisan,  class_name: 'User'
  
  has_one  :product_category
  has_one  :palette
  has_many :design_versions

  accepts_nested_attributes_for :product_category
  accepts_nested_attributes_for :palette
# 

  def artisan_assigned?
    self.artisan_id ? true : false
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  def index 
    @projects = Project.where("#{current_user.role}_id =?", current_user.id)
  end

  def show
    @project  = Project.find(params[:id])
    @products = Product.where("project_id=?", @project.id)
    @product_category_ids = @products.map { |product| product.product_category_id }
    @palettes = Palette.where("product_category_id=?", @product_category_ids)
  end

  def new
    @project = Project.new
    @project.build_palette
  end

  def edit
    @project = Project.find(params[:id])
    session[:project_id] = @project.id
    session[:counter] = @project.design_versions.all.size

    if @project.artisan_assigned?
      @attribute_layers = User.find(@project.artisan_id).palettes.first.attribute_layers
      @attribute = []
      @attribute_layers.each do |al|
        @attribute += al.attributes
      end
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to :index
    else
      render :edit
    end
  end

  def create   
    @project = Project.new(params[:project])
    current_user.customer? ? @project.customer = current_user : @project.artisan = current_user

    if @project.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to action: :index
  end
  
  def palette
    @project = Project.find(session[:project_id])
  end
  
  def category
    @project = Project.find(session[:project_id])
  end
  
  def attribute_layer
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_attribute_fields.html.erb
<fieldset>
	<%= f.label :label, "Attribute label" %>
	<%= f.text_field :label %>
    <%= f.file_field :attr_img %> <br>
</fieldset>

app/views/projects/_attribute_layer_fields.html.erb
<fieldset>
	<%= f.label :label, "Attribute layer label" %>
	<%= f.text_field :label %>
	<%= f.label "Attributes"%>
	  	<%= f.collection_check_boxes :attribute_ids, Attribute.all, :id, :label do |b| 
	                     b.label { b.check_box + ' ' + b.text } 
	                     end  %>
    <%= f.simple_fields_for :attribute do |builder| %>
        <%= render 'attribute_fields', f: builder %>
    <% end %>
</fieldset>

app/views/projects/_design_partial.html.erb
<!-- <div id="wrapper_container">
  <div class="span9 unselectable" id="canvas_container">
    <button class="btn pull-left" id="reset">Reset</button>
    <button class="btn pull-left" id="remove-img">Remove Image</button>
    <button class="btn pull-left" id="switch">Switch User</button>

    <canvas id="canvas"></canvas>
    <div id="wPaint"></div>

  </div>
</div> -->

app/views/projects/_palette_fields.html.erb
<fieldset>
	<%= f.label :label, "Palette label" %>
	<%= f.text_field :label %>
	<%= f.label "Attribute Layers"%>
	  	<%= f.collection_check_boxes :attribute_layer_ids, AttributeLayer.all, :id, :label do |b| 
	                     b.label { b.check_box + ' ' + b.text } 
	                     end  %>
    <%= f.simple_fields_for :attribute_layer do |builder| %>
        <%= render 'attribute_layer_fields', f: builder %>
    <% end %>
</fieldset>

app/views/projects/_product_category_fields.html.erb
<fieldset>
	<%= f.label :label, "Category label" %>
	<%= f.text_field :label %>
</fieldset>

app/views/projects/category.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.select :product_category_id, ProductCategory.all.map { |r| [r.label, r.id] }, include_blank: false  %><br>
  <%= f.button :submit, "Save and continue" %>
<% end %>

<%= link_to 'Create Category', new_product_category_path %>

app/views/projects/design.html.erb
      <div class="row span12 bordered" id="design">
        <div class="span2" id="pallete">

          <div class="menu_ bordered">
            <select id=attr-select>
              <option value="1">Patterns</option>
              <option value="2">Stitch type</option>
              <option value="3">Mirror Work</option>
              <option value="4">Button</option>
            </select>

            <div id=choice1 class=choice>
              <img src="/pictures/Patterns/pattern1.jpg" _width="90px" class="attr">
              <img src="/pictures/Patterns/pattern3.jpg" _width="90px" class="attr">
              <img src="/pictures/Patterns/pattern4.jpg" _width="90px" class="attr">
              <img src="/pictures/Patterns/pattern5.jpg" _width="90px" class="attr">
              <img src="/pictures/Patterns/pattern6.jpg" _width="90px" class="attr">
              <img src="/pictures/Patterns/pattern7.jpg" _width="90px" class="attr">
              <img src="/pictures/Patterns/pattern8.jpg" _width="90px" class="attr">
              <img src="/pictures/Patterns/pattern9.jpg" _width="90px" class="attr">
              <img src="/pictures/Patterns/pattern10.jpg" _width="90px" class="attr">
              <img src="/pictures/Patterns/pattern11.jpg" _width="90px" class="attr">
              <img src="/pictures/Patterns/pattern12.jpg" _width="90px" class="attr">
            </div>

            <div id=choice2 class=choice>
              <img src="/pictures/Stitches/stich1.jpg" _width="90px" class="attr">
              <img src="/pictures/Stitches/stich2.jpg" _width="90px" class="attr">
              <img src="/pictures/Stitches/stich3.jpg" _width="90px" class="attr">
              <img src="/pictures/Stitches/stich4.jpg" _width="90px" class="attr">
              <img src="/pictures/Stitches/stich5.jpg" _width="90px" class="attr">
              <img src="/pictures/Stitches/stich6.jpg" _width="90px" class="attr">
              <img src="/pictures/Stitches/stich7.jpg" _width="90px" class="attr">
              <img src="/pictures/Stitches/stich8.jpg" _width="90px" class="attr">
              <img src="/pictures/Stitches/stich9.jpg" _width="90px" class="attr">
              <img src="/pictures/Stitches/stich10.png" _width="90px" class="attr">
              <img src="/pictures/Stitches/stich11.jpg" _width="90px" class="attr">
              <img src="/pictures/Stitches/stich12.jpg" _width="90px" class="attr">
            </div>

            <div id=choice3 class=choice>
              <img src="/pictures/Mirror Work/m1.jpg" _width="90px" class="attr">
              <img src="/pictures/Mirror Work/m2.jpg" _width="90px" class="attr">
              <img src="/pictures/Mirror Work/m3.jpg" _width="90px" class="attr">
              <img src="/pictures/Mirror Work/m4.jpg" _width="90px" class="attr">
              <img src="/pictures/Mirror Work/m5.jpg" _width="90px" class="attr">
              <img src="/pictures/Mirror Work/m6.jpg" _width="90px" class="attr">
              <img src="/pictures/Mirror Work/m7.jpg" _width="90px" class="attr">
              <img src="/pictures/Mirror Work/m8.jpg" _width="90px" class="attr">
              <img src="/pictures/Mirror Work/m9.jpg" _width="90px" class="attr">
              <img src="/pictures/Mirror Work/m10.jpg" _width="90px" class="attr">
              <img src="/pictures/Mirror Work/m11.jpg" _width="90px" class="attr">
              <img src="/pictures/Mirror Work/m12.jpg" _width="90px" class="attr">
            </div>

            <div id=choice4 class=choice>
              <img src="/pictures/Buttons/button1.jpg" _width="90px" class="attr">
              <img src="/pictures/Buttons/button2.jpg" _width="90px" class="attr">
              <img src="/pictures/Buttons/button3.jpg" _width="90px" class="attr">
              <img src="/pictures/Buttons/button4.jpg" _width="90px" class="attr">
            </div>

          </div>

        </div>

        <div class="span9 unselectable" id="canvas_container">
          <button class="btn pull-left" id="reset">Reset</button>
          <button class="btn pull-left" id="remove-img">Remove Image</button>
          <button class="btn pull-left" id="switch">Switch User</button>
          <%= form_for @project, :url =>{ action: :design }, :html => { :multipart => true } do |form| %>
            <%= form.file_field :base_image %>
            <%= form.button "Upload Image" %>

          <% end %>

          <input id=baseimage type="hidden" value= <%=@new_image_url%> />
          <input id=projectid type="hidden" value= <%=@project.id %> />
          <button class="btn pull-left" id="save-project">Save Project</button>

          <canvas id="canvas">
          </canvas>
        </div>
      </div> <!-- /row -->

app/views/projects/design_partial.html.erb
<div id="container">
  <div class="span9 unselectable" id="canvas_container">
    <button class="btn pull-left" id="reset">Reset</button>
    <button class="btn pull-left" id="remove-img">Remove Image</button>
    <button class="btn pull-left" id="switch">Switch User</button>

    <canvas id="canvas"></canvas>
    <div id="wPaint"></div>

  </div>
</div>

app/views/projects/index.html.erb
<h4>Listing projects for <%= current_user.name %> </h4>
 
<table class="projects-table">
  <tr>
    <th>Title</th>
    <th>Summary</th>
	<th>File</h1>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Remove', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br /> <br />
<% if user_signed_in? %>
  <li><%= link_to 'New project', new_project_path %></li>
<% end %>


<style>
.projects-table tr td{
    padding: 15px;
}
</style>

app/views/projects/new.html.erb
<%= simple_form_for @project, url_path: projects_path, html: { multipart: true } do |f| %>

  <div id="tabs">

    <ul>
      <li><a href="#tabs-1">Project</a></li>
      <li><a href="#tabs-2">Product Category</a></li>
      <li><a href="#tabs-3">Palette</a></li>
    </ul>
    
    <div id="tabs-1">
      <%= f.input :name %>
      <%= f.input :description, as: :text %>
    </div>

    <div id="tabs-2">
      Choose a file
      <%= f.file_field :img_file %> <br>
      
      Or createa a new category
      <%= f.simple_fields_for :product_category do |builder| %>
        <%= builder.input :label, :label => false, :placeholder => "ProductCategory Label" %>
      <% end %>
    </div>
    
    <div id="tabs-3">

      Or create a new palette:
      <%= f.simple_fields_for :palette do |builder| %>
        <%= render 'palette_fields', f: builder %>
      <% end %>




      <%= f.button :submit, "Create" %>
    </div>


  </div>

<% end %>

<style>
textarea, input {
    max-height: 200px;
    width: 400px;
}
</style>

  <script>
  $(function() {
    $( "#tabs" ).tabs();
  });
  </script>

app/views/projects/palette.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.select :palette_id, Palette.all.map { |r| [r.label, r.id] }, include_blank: false  %><br>
  <%= f.button :submit, "Save and continue" %>
<% end %>

<%= link_to 'Create Palette', new_palette_path %>

app/views/projects/show.html.erb
<h3> Project <%=@project.id=%> </h3>
<table class="project">
    <tr>
        <td>Project Name: </td><td><%=@project.name=%></td>
    </tr>
    <tr>
        <td>Project Description:</td> <td><%=@project.description=%></td>
    </tr>
    <tr>
       <td><%= "#{current_user.role}" %> :</td> <td><%=current_user.name %></td>
    </tr>
    <tr>
        <td>Last Updated At:</td> <td><%=@project.updated_at=%>
    </tr>
    <tr>
        <td>Created At:</td> <td><%=@project.created_at=%></td>
    </tr>
</table>

<br />


<br /><br /><br />
<h4>Products associated with this Project</h4>
<table>
  <tr>
    <th>Name</th>
    <th>Summary</th>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td>
    <%= image_tag @project.img_file.url(:medium) %></td>
      <td><%= link_to 'Show', product %></td>
    </tr>
  <% end %>
</table>
<br /><br /><br />

<%= link_to 'New product', new_product_path(project_id: @project.id) %>


<br /><br /><br />


<h4>Palettes associated with this Project</h4>
<table>
  <tr>
    <th>Name</th>
    <th>Link</th>
  <% @palettes.each do |palette| %>
    <tr>
      <td><%= palette.label %></td>
      <td><%= link_to 'Show', palette %></td>
    </tr>
  <% end %>
</table>


<style>
tr td, tr th{
    min-width: 150px;
    padding: 2px;
    text-align: left;
}
</style>