config/routes.rb
ArtisanMarket::Application.routes.draw do
  
  resources :attribute_layers

  resources :attributes

  devise_for :users

  get "pages/home"
  get "pages/about"
  get "pages/contact"

  resources :products
  resources :projects do
    member do 
      post :attribute_layer
      get :palette
      get :category
    end
  end
  resources :product_categories
  resources :palettes
  resources :attribute_layers
  resources :attributes
  resources :catalogues
  resources :design_versions

  root to: 'pages#home'

end

app/models/catalogue.rb
class Catalogue < ActiveRecord::Base
  attr_accessible :label, :description, :product_ids

  belongs_to :user

  has_many :products
end

app/controllers/catalogues_controller.rb
class CataloguesController < ApplicationController

  before_filter :authenticate_user!

  def index
    @catalogues = Catalogue.where("user_id =?", current_user.id)
    if current_user.customer?
      @artisans = User.all.select { |user| user.artisan? }
      @artisans.each do |artisan|
        @catalogues += artisan.catalogues
      end
    end
  end

  def show
    @catalogue = Catalogue.find(params[:id])
    @products = Product.where("catalogue_id=?", @catalogue.id)
  end

  def new
    @catalogue = Catalogue.new()
  end

  def edit
    @catalogue = Catalogue.find(params[:id])
    @products  = Product.where("user_id =?", current_user.id)
  end

  def update
    @catalogue = Catalogue.find(params[:id])
    if @catalogue.update_attributes(params[:catalogue])
      redirect_to action: :index
    else
      render :edit
    end
  end

  def create
    @catalogue = Catalogue.new(params[:catalogue])
    @catalogue.user = current_user
    @catalogue.save
    redirect_to action: :index
  end

  def destroy
    @catalogue = Catalogue.find(params[:id])
    @catalogue.destroy
    redirect_to action: :index
  end

end

app/helpers/catalogues_helper.rb
module CataloguesHelper
end

app/views/catalogues/edit.html.erb
<%= simple_form_for @catalogue, html: { multipart: true } do |f| %>
  <%= f.input :label %>
  <%= f.input :description, as: :text %>
  
  <%= f.association :products,
                    label: "Add Products to this catalogue",
                    :collection => current_user.products { |p| [p.name, p.id ] },
                    :as => :check_boxes,
                    :selected => @catalogue.products %>
  <%= f.button :submit %>

<% end %>

<style>
textarea, input {
    max-height: 200px;
    width: 400px;
}
</style>

app/views/catalogues/index.html.erb
<h3>Listing Catalogues for <%= current_user.name %> </h3>
 
<table class="catalogues-table">
  <tr>
    <th>Title</th>
    <th>Summary</th>
	  <th>Owner</h1>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @catalogues.each do |catalogue| %>
  <tr>
    <td><%= catalogue.label %></td>
    <td><%= catalogue.description %></td>
    <td><%= catalogue.user.name %></td>

    <td><%= link_to 'Show', catalogue %></td>
    <td><%= link_to 'Edit', edit_catalogue_path(catalogue) %></td>
    <td><%= link_to 'Remove', catalogue, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>


<br />
<br />  
<%= link_to 'New Catalogue', new_catalogue_path %>

<style>
.catalogues-table tr td{
    padding: 15px;
}
</style>

app/views/catalogues/new.html.erb
<%= simple_form_for @catalogue, html: { multipart: true } do |f| %>
  <%= f.input :label %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit %>
<% end %>

<style>
textarea, input {
    max-height: 200px;
    width: 400px;
}
</style>

app/views/catalogues/show.html.erb
<h3> Catalogue <%=@catalogue.id=%> </h3>
<table class="catalogue">
    <tr>
        <td>Catalogue Name: </td><td><%=@catalogue.label=%></td>
    </tr>
    <tr>
        <td>Catalogue Description:</td> <td><%=@catalogue.description=%></td>
    </tr>
    <tr>
       <td>User:</td> <td><%= @catalogue.user.name %></td>
    </tr>
    <tr>
        <td>Last Updated At:</td> <td><%=@catalogue.updated_at=%>
    </tr>
    <tr>
        <td>Created At:</td> <td><%=@catalogue.created_at=%></td>
    </tr>
</table>

<br />

<h4>Products associated with this catalogue</h4>
<table>
  <tr>
    <th>Name</th>
    <th>Summary</th>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= image_tag product.project.img_file.url(:thumb) %></td>

      <td><%= link_to 'Show',   product %></td>
      <% if current_user==@catalogue.user %>
        <td><%= link_to 'Edit',   edit_product_path %></td>
        <td><%= link_to 'Delete', product %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'Edit Catalogue', edit_catalogue_path(catalogue_id: @catalogue.id) %>

<style>
tr td, tr th{
    /*min-width: 150px;*/
    padding: 5px;
    text-align: left;
}
</style>